workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 20
    instance_type: linux
    
    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
