workflows:
  android-build:
    name: Build Android APK
    # Não usamos 'environment: android:' aqui (causa validação inválida)
    scripts:
      - name: Ensure gradlew is executable
        script: |
          chmod +x gradlew || true
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - elielcornelio58@gmail.com
